global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # AI FTES Backend (via host network - different Docker network)
  - job_name: "ai-ftes-backend"
    static_configs:
      - targets: ["172.17.0.1:7860"] # Backend accessible via host network
    metrics_path: "/metrics"
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_timestamps: true
    honor_labels: true

  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Node Exporter - System metrics
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 15s
    metrics_path: "/metrics"

  # Loki metrics
  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]
    metrics_path: "/metrics"
    scrape_interval: 15s

  # Promtail metrics
  - job_name: "promtail"
    static_configs:
      - targets: ["promtail:9080"]
    metrics_path: "/metrics"
    scrape_interval: 15s

# Alerting
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
