auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

limits_config:
  ingestion_rate_mb: 64
  ingestion_burst_size_mb: 128
  max_entries_limit_per_query: 10000
  max_streams_per_user: 10000
  max_line_size: 256KB

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093

# By default, Loki will send anonymous usage information to Grafana Labs.
# This allows us to learn how many people use Loki, what features are most
# used, and how often they are used. This data is never sold to 3rd parties.
analytics:
  reporting_enabled: false 